version: '3'
services:
  post:
    build:
      context: ./post
    restart: "no"
    hostname: ${POST_HOST}
    ports:
      - ${POST_PORT}:${POST_PORT}
    env_file:
      - ./.env
      - ./post/.${NODE_ENV}.env
    networks:
      - backend
    volumes:
      - ./post/:/var/www/post
      - /var/www/post/node_modules
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
      - rabbitmq
